### ISSUE TITLE
node js version 10 is not supported anymore

### ISSUE THREAD

**Issue by rodiali1** [AndyW22/todolist-app#1]
Hello,

Do you have any plans to update the NodeJS version from 10 to a newer version as AWS Lambda doesn't support version 10 anymore?

Thanks

**Comment by AndyW22** [comment]
Which lambdas are you referring to? This repo doesnt have any lambdas apart from possibly the unused default ones  by in cognito, which is using NodeJS 12.

**Comment by rodiali1** [comment]
Yes exactly I'm referring to the one that gets created with Cognito, in my case they (at least the one that is failing) use NodeJS 10 which fails to be created 

> Following resources failed
> 
> Resource Name: amplify-todolist-xxxx-a-UserPoolClientLambda-xxxx (AWS::Lambda::Function)
> Event Type: create
> Reason: Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs16.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: xxxx)" (RequestToken: xxxx, HandlerErrorCode: InvalidRequest)

How to reproduce:

- Clone the repo
- amplify init
- Delete yarn.lock file
- yarn install
- amplify push

I've tried to change it in amplify/backend/auth/todolist/todolist-cloudformation-template.yml line 244 but that seems to break the build phase after adding hosting (not sure yet if this is the root cause)

**Comment by AndyW22** [comment]
I have updated auth based on the amplify CLI updates so the cloudformation template is in json and the UserPoolClientLambda is now using NodeJS v14. Please re-open if the error is still present.
