### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by rodiali1** [AndyW22/todolist-app#4]
Here comes me again :) 

The application doesn't compile and run when doing `yarn start`

This is what I get in the terminal 

> Failed to compile.
> 
> /Users/xxxx/Desktop/todolist-app/src/redux/store.ts
> TypeScript error in /Users/xxxx/Desktop/todolist-app/src/redux/store.ts(41,41):
> Argument of type '{ key: string; storage: WebStorage; whitelist: string[]; }' is not assignable to parameter of type 'PersistConfig<CombinedState<{ todos: Todo[]; user: CognitoUserInterface; theme: boolean; }>, any, any, any>'.
>   Types of property 'storage' are incompatible.
>     Property 'getAllKeys' is missing in type 'WebStorage' but required in type 'Storage'.  TS2345
> 
>     39 |   whitelist: ['theme'],
>     40 | };
>     41 | const persistedReducer = persistReducer(persistConfig, reducers);
>          |                                         ^
>     42 | 
>     43 | const store = configureStore({
>     44 |   reducer: persistedReducer,
>

**Comment by AndyW22** [comment]
Im not able to reproduce this, are you able to try adding the following:
```

export type RootReducer = ReturnType<typeof reducers>;

const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['theme'],
};
const persistedReducer = persistReducer<RootReducer, any>(
  persistConfig,
  reducers,
);
```

If this does not work, I am not sure what is causing that - I presume you are using the correct versions. Is this error also occuring on `yarn build` ?

**Comment by rodiali1** [comment]
I still have the same issue, I had another issue before this appeared where I had to 
`yarn add @types/react@latest @types/react-dom@latest --dev`
`yarn add react@latest react-dom@latest `

Yes, I get the same error with `yarn build`

**Comment by AndyW22** [comment]
If you installed the lastest then you have upgraded the app to React v18, there will likely be bugs with other packages that havent been upgraded to v18. That will be whats causing this error, you can try upgrading redux-persist to the latest version as well, but bear in mind there will be many more errors on the app since v18 had a lot of breaking changes.

**Comment by rodiali1** [comment]
Not sure if I should open a new issue or not, let me know if you want that please
I have rolled back to the same version as you had (17.0.0) and I get this error now (which was the reason why I upgraded to the latest react v)

> Failed to compile.
> 
> /Users/xxxxx/Desktop/todolist-app/src/Header.tsx
> TypeScript error in /Users/xxxxx/Desktop/todolist-app/src/Header.tsx(38,10):
> 'Box' cannot be used as a JSX component.
>   Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.  TS2786
> 
>     36 |           size={60}
>     37 |         />
>    38 |         <Box mr={2} display="flex" alignItems="center">
>        |          ^
>     39 |           <Button
>     40 |             color="primary"
>     41 |             variant="contained"
>

**Comment by AndyW22** [comment]
please see https://github.com/mui/material-ui/issues/32245 , may be a yarn issue.

**Comment by AndyW22** [comment]
> > Not sure if I should open a new issue or not, let me know if you want that please I have rolled back to the same version as you had (17.0.0) and I get this error now (which was the reason why I upgraded to the latest react v)
> > ```
> > Failed to compile.
> > 
> > /Users/rodi/Desktop/todolist-app/src/Header.tsx
> > TypeScript error in /Users/rodi/Desktop/todolist-app/src/Header.tsx(38,10):
> > 'Box' cannot be used as a JSX component.
> >   Its element type 'ReactElement<any, any> | Component<BoxProps, any, any> | null' is not a valid JSX element.  TS2786
> > 
> >     36 |           size={60}
> >     37 |         />
> >    38 |         <Box mr={2} display="flex" alignItems="center">
> >        |          ^
> >     39 |           <Button
> >     40 |             color="primary"
> >     41 |             variant="contained"
> > ```
> 
> The above was indeed a yarn issue.
> 
> But even with npm I still get the main error this issue is about, unfortunately :(
> 
> Do you have any other advice what could be the issue?

Only other ideas I have would be using `npm install --force`, upgrading npm to latest version, or just casting as `any`. As i cannot replicate this issue I'm not able to help much with debugging it.

**Comment by rodiali1** [comment]
So for now, I cast `persistConfig`  as `any` and it is compiling and running as it should be.
